appimagetool.nix

Had to add the following to make it work with chroot's enabled in builds (build-use-sandbox = true)

Fix building appimagetool with build chroots enabled.

---

AppRun.c
Makefile
appdir.nix
appimagetool.nix

- Various fixes for AppImage functionality
- Fixup appdata linkage
- Add squashfsTools in case it's not available.
- AppRun.c is based on the original AppRun.c but it has some pieces from nix-user-chroot in it to get the /nix/ dir linked up.
- All environment variables that carry over are listed in AppRun.c for now. Eventually, 
@probonopd I'm not sure how to do the license correctly for AppRun.c. I based it on your original  AppRun.c so I left the header, but I've added nix-user-chroot code as well as some of my own. See lethalman/nix-user-chroot#8.
Any other suggestions/comments would be helpful. It's still pretty much a hack.

New AppRun executable for AppImages

---

default.nix
nix-user-chroot/Makefile
nix-user-chroot/main.cpp

pulled nix-user-chroot into the same repo
put the startup command into a bash script, so the tarball job knows its deps
changed nix-user-chroot into a c++ program
added CLI flags to allow configuring the sandbox it produces
with these changes, you can now configure it to do things like mapping the host /etc to /host-etc inside the namespace, and have finer control over how pure the env variables are

overhaul most of nix-bundle

---

AppRun.c
appdir.nix
appimage-top.nix
appimagetool.nix
test-appimage.nix

Builds on top of #26 
* Fixes #24 (using mostly the suggested approach)
* Fixes to work with latest nixpkgs which does not have musl-gcc, instead just use musl-native stdenv
* minor cleanup to use dynamicLinker string from bintools, but might not want this since requires however-recent nixpkgs.  Shrug.
* Updated appimagetool to 10 and reverted, didn't explore what broke :innocent:
* Add a really quick nix file for patchelf'ing appimage's generated so they execute.
With these, was able to do:
```console
$ NIX_PATH=nixpkgs=channel:nixos-unstable ./nix2appimage.sh vlc
$ NIX_PATH=nixpkgs=channel:nixos-unstable nix build -f test-appimage.nix --arg appimagefile ./VLC*AppImage
$ ./result
<VLC runs>
```
Don't have immediate access to a non-NixOS machine with a display server (and new-enough …

Misc fixups that may be of interest (don't merge as-is)

---

default.nix

with `-rm!` present, this results in a ~300mb tmp directory being left in `/tmp` for every single invocation of the bundle

auto-delete the tmpdir when finished

---

nix-user-chroot/main.cpp

under debian, user namespaces are disabled by default, this error detects the fault and gives directions on how to enable them

give directions on how to fix namespaces when they are disabled

---

appimage.nix
default.nix

This was needed for me to use nix-bundle, specifically the AppImage tool. Roughly, appimage needs write access to the AppDir.

relocation to allow writing

---

default.nix

`[pid  2158] execve("./nix/store/9ymkjxrd09pjmjnmvqzibz5sydqafz0c-startup", ["./nix/store/9ymkjxrd09pjmjnmvqzi"...], [/* 64 vars */]) = -1 ENOENT (No such file or directory)`
if you try to execute a `+x`'d script that lacks a `#!` line, the linux kernel will fail with the above error
but if `/bin/sh` is bash based, it will auto-detect that, and silently do the right thing, so the mistake goes un-noticed
however, ubuntu uses dash for `/bin/sh`, and that appears to lack the same intelligence

fix the startup script to run on dash based systems

---

appdir.nix
appimage-bundle.nix

Create fake icon and .desktop to bundle most CLI applications
Usage: nix-build appimage-bundle.nix --argstr package hello --argstr exec hello
This makes it easier to create an appimage executable for CLI applications that lack icons or .desktop files.

Appimage bundler

---

appdir.nix
appimage-bundle.nix

Removed some dependencies that are not needed and added the ability to put a nix expression into the package argument.
Example (note the --arg vs --argstr for the package argument):
nix-build appimage-bundle.nix --arg package 'with import <nixpkgs>{}; writers.writePython3Bin "helloThere.py" {} "print(1)\n"' --argstr exec helloThere.py

Allow bundle to handle an evaluated nix expression

---

nix-bundle.sh

Possible solution to #47.
TODOs:

nix-bundle.sh: Modernize CLI

---

AppRun.c

If the content of the appimage contains $out/bin/sh, then /bin/sh exists
and system() works.

symlink /bin to /usr/bin

---

nix-bundle.sh

When nix-bundle is invoked without a TTY, output the store path instead
of catting the content. This allows more flexibility.

nix-bundle: print the output path instead

---

flake.nix

Before:
```
$ /nix/store/10bnmxbki7mhwaacs605m8fjiswg3jdv-arx -c "echo abc"
Open On-Chip Debugger 0.10.0+dev-snapshot (2021-01-18-22:12)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
Unexpected command line argument: abc
```
After:
```
$ /nix/store/l6g76xbmna092aads0plbvz7z962ygrn-arx -c "echo abc"
Open On-Chip Debugger 0.10.0+dev-snapshot (2021-01-18-22:12)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
abc
...
```

Add missing quotes

---

default.nix

The previous check was actually not differentiating between the two
cases defined in `test.sh` (both cases were ignore and the if branch was
never used).
By using `isDerivation` we now properly distinguish between the two
cases, and add the missing context when necessary.
/cc @zimbatm

Properly differentiate between derivation and store path.

---

nix-user-chroot/Makefile

Without this cross-compiling and compiling static binaries is broken.
---
Aside: we could compile nix-user-chroot as a static binary instead of patching the binary to use local nix store.

User proper compiler for nix-user-chroot

---

default.nix

There was a change in nixpkgs recently, which requires to explicitly define `libgcc_s`. Right now the bundled package builds successfully but complains that there's no `libgcc_s.so.1` when `nix-user-chroot` is started.

fix for libgcc_s.so.1 linking issue

---

README.md

I guess you meant [Snap](https://en.wikipedia.org/wiki/Snap_(software)), instead of `snappy`.

doc: fix snappy typo

---

default.nix

In our project produce binary reproducible binaries, and we would like to build, release and sign bundled versions as well.
However currently the resulting files are not reproducible. After some investigation I've narrowed it down to non-deterministic `tar` invocation.
This PR changes it to something I've found online, and I verified that binaries between two machines produce byte-identical bundled binary.

fix tar archive reproducibility

---

default.nix

`QualifiedPath` https://www.github.com/solidsnack/arx/blob/7561fed76bb613302d1ae104f0eb2ad13daa9fac/System/Posix/ARX/CLI/CLTokens.hs#L30
Fixes https://github.com/nix-community/nix-bundle/issues/108
Fixes https://github.com/nix-community/nix-bundle/issues/52

Fix placing files in `$HOME/.cache`
